layout_spectrum: 0.5957534208428115
typography_spectrum: 0.3866554026026279
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.32737836288288236
  lightness: 0.7194486169610173
  saturation: 0.5327832030598074
  rhythmicContrast: 0.14702460658736527
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alastair Thompson
  email: 'althelion@gmail,com'
  url: www.scoop.co.nz
name: Crucible
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Scoop
    url: 'http://www.scoop.co.nz'
    type: external
favicon: null
title: Alastair Thompson
description: A Kiwi journalist in Europe
purpose: []
