name: Crucible
favicon: null
layout_spectrum: 0.9025718227494508
typography_spectrum: 0.6844659801572561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4532027302775532
  lightness: 0.5380865167826414
  saturation: 0.5707021988928318
  rhythmicContrast: 0.4409431244712323
purpose: []
