typography_spectrum: 0.607158494181931
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.8754783014301211
  lightness: 0.945622337050736
  saturation: 0.7275470071472228
  rhythmicContrast: 0.7894510903861374
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04058645898476243
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alastair Thompson
  email: 'althelion@gmail,com'
  url: www.scoop.co.nz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fda9978c-8ae8-4d83-996d-621f2ac99012.jpg
name: Crucible
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Scoop
    url: 'http://www.scoop.co.nz'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47a4c878-e926-4703-9696-11240203d4d6.jpg
title: Alastair Thompson
description: A Kiwi journalist in Europe
purpose: []
