typography_spectrum: 0.607158494181931
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.8754783014301211
  lightness: 0.945622337050736
  saturation: 0.7275470071472228
  rhythmicContrast: 0.7894510903861374
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04058645898476243
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alastair Thompson
  email: 'althelion@gmail,com'
  url: www.scoop.co.nz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/57ccd6ba-d617-4216-a24a-952b524ddb57.jpg
name: Crucible
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Scoop
    url: 'http://www.scoop.co.nz'
    type: external
  - name: Earthworm
    url: 'http://earthworm.net'
    type: external
  - name: La Révolution Pacifique
    url: 'https://mazuel2017.fr/'
    type: external
  - name: Scoop Foundation
    url: 'http://foundation.scoop.co.nz'
    type: external
  - name: Reinventing News
    url: >-
      http://www.scoop.co.nz/stories/HL1501/S00058/reinventing-news-as-a-public-right-a-public-conversation.htm
    type: external
  - name: Ethical Paywall
    url: >-
      http://www.scoop.co.nz/stories/HL1506/S00051/how-scoops-ethical-paywall-model-has-changed-everything.htm
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/256fdb13-3238-4d89-ba9e-b9c6055e9941.jpg
title: Alastair Thompson
description: A Kiwi journalist in Europe
purpose: []
