layout_spectrum: 0.04058645898476243
typography_spectrum: 0.607158494181931
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.8754783014301211
  lightness: 0.945622337050736
  saturation: 0.7275470071472228
  rhythmicContrast: 0.7894510903861374
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alastair Thompson
  email: 'althelion@gmail,com'
  url: www.scoop.co.nz
name: Crucible
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Scoop
    url: 'http://www.scoop.co.nz'
    type: external
favicon: null
title: Alastair Thompson
description: A Kiwi journalist in Europe
purpose: []
